version: '{build}'

pull_requests:
  do_not_increment_build_number: true

environment:
  NUGET_API_KEY:
    secure: Wer0Q76HZrLMMVewwxg4HEIHGsBwAgmecbRYgD4dedxC96Ektuj2ftrfWMTCVgzF

nuget:
  project_feed: true
  disable_publish_on_pr: true

build_script:
  - ps: ./build.bat

artifacts:
  - path: build\Sharp9P.dll
  - path: build\Sharp9P.pdb
  - path: packaging\*.nupkg
  
deploy: off
